/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  theme: {

    container: {
      center: true,
      padding: '0.1rem'
    },
    extend: {
      fontFamily: {
        "vazir": "vazir",
        "vazirLight": "vazir light",
        "vazirBold": "vazir bold",
      },
      colors: {
        "main": "#3e7bfa",
        "main-darker": "#004fc4",
        "main-lighter": "#6698fa",
        "dark-0": "#1c1c28",
        "dark-1": "#28293d",
        "dark-2": "#555770",
        "dark-3": "#8f90a6",
        "dark-4": "#c7c9d9",
        "light-0": "#e4e4eb",
        "light-1": "#ebebf0",
        "light-2": "#f2f2f5",
        "light-3": "#fafafc",
        "light-4": "#fff",
        "red-0": "#e63535",
        "red-1": "#ff3b3b",
        "red-2": "#ff5c5c",
        "red-3": "#ff8080",
        "red-4": "#ffe6e6",
        "green-0": "#05a660",
        "green-1": "#06c270",
        "green-2": "#39d98a",
        "green-3": "#57eba1",
        "green-4": "#e3fff1",
        "teal-0": "#00b7c4",
        "teal-1": "#00cfde",
        "teal-2": "#73dfe7",
        "teal-3": "#a9eff2",
        "teal-4": "#e5ffff",
        "blue-0": "#004fc4",
        "blue-1": "#0063f7",
        "blue-2": "#5b8def",
        "blue-3": "#9dbff9",
        "blue-4": "#e5f0ff",
        "yellow-0": "#e5b800",
        "yellow-1": "#fc0",
        "yellow-2": "#fddd48",
        "yellow-3": "#fded72",
        "yellow-4": "#fffee5",
        "orange-0": "#e57a00",
        "orange-1": "#f80",
        "orange-2": "#fdac42",
        "orange-3": "#fccc75",
        "orange-4": "#fff8e5",
        "purple-0": "#4d0099",
        "purple-1": "#60c",
        "purple-2": "#ac5dd9",
        "purple-3": "#dda5e9",
        "purple-4": "#ffe5ff",
      }
    },
  },
  plugins: [],
}

